#!/bin/bash

# init will deploy vault only and ensure it is initialised.
set -x

terragrunt run-all apply --terragrunt-source-update --terragrunt-source-map --terragrunt-non-interactive
# terragrunt run-all apply --terragrunt-source-update --terragrunt-source-map github.com/firehawkvfx/firehawk-main.git=$TF_VAR_firehawk_path --terragrunt-non-interactive
