#!/bin/bash

function retrieve_file {
  local -r source_path="$1"
  if [[ -z "$2" ]]; then
    local -r target_path="$source_path"
  else
    local -r target_path="$2"
  fi
  echo "Aquiring vault data... $source_path to $target_path"
  response=$(/usr/local/bin/retry \
  "vault kv get -field=value $source_path/file" \
  "Trying to read secret from vault")

  echo "mkdir: $(dirname $target_path)"
  mkdir -p "$(dirname $target_path)" # ensure the directory exists
  echo "Check file path is writable: $target_path"
  if test -f "$target_path"; then
    echo "File exists: ensuring it is writeable"
    chmod u+w "$target_path"
    touch "$target_path"
  else
    echo "Ensuring path is writeable"
    touch "$target_path"
    chmod u+w "$target_path"
  fi
  if [[ -f "$target_path" ]]; then
    chmod u+w "$target_path"
  else
    echo "Error: path does not exist, var may not be a file: $target_path "
  fi
  echo "Write file content: single operation"
  echo "$response" | base64 --decode > $target_path
  if [[ ! -f "$target_path" ]] || [[ -z "$(cat $target_path)" ]]; then
    echo "Error: no file or empty result at $target_path"
    exit 1
  fi
  echo "retrival done."
}

retrieve_file "$@"