- name: get groups
  shell: |
    /opt/Thinkbox/Deadline10/bin/deadlinecommand GetGroupNames
  register: result

- name: add groups
  shell: |
    /opt/Thinkbox/Deadline10/bin/deadlinecommand -AddGroup {{ item }}
  when: 'item | string not in result.stdout'
  with_items:
  - local
  - cloud
  - cloud_engine
  - cloud_c2_engine
  - cloud_c8_engine
  - cloud_c64_engine
  - cloud_c2_mantra
  - cloud_c8_mantra
  - cloud_c64_mantra
  - cloud_mantra
  - local_workstation
  - cloud_workstation
  - local_all
  - cloud_all