version: 0.0
os: linux
# permissions:
#   - object: /tmp/my-app/my-folder-2
#     pattern: "**"
#     except: [my-file-8.txt]
#     owner: ec2-user
#     mode: 777
#     type:
#       - file
hooks:
  BeforeInstall:
    - location: scripts/install_log_agent
      timeout: 300
      runas: root
  Install:
    - location: scripts/install-packages
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/install-packages
      timeout: 300
      runas: ec2-user
    - location: init/init # ensure all requirement are initialised (SSH keys, S3 buckets, profiles etc)
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
      runas: ec2-user