version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/git_pull
      timeout: 300
      runas: root
    - location: install-packages
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
      runas: root