version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/install_log_agent
      timeout: 300
      runas: root
    - location: install-packages-instance
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/apply # apply will create or destroy depending on the env vars present
      timeout: 3600 # 1 hour timeout.
      runas: ec2-user
  # ApplicationStop:
  #   - location: deploy/destroy
  #     timeout: 3600 # 1 hour timeout.
  #     runas: ec2-user
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
      runas: ec2-user