version: 0.2

env:
  variables:
    resourcetier: dev
  parameter-store:
    onsite_public_ip: "/firehawk/resourcetier/$resourcetier/onsite_public_ip"

phases:
  pre_build:
    commands:
      - python3 -m pip install --user --upgrade pip
      - python3 -m pip install ansible boto3 botocore
  install:
    commands:
      - git status
      - ./gitpullrecursive --init-all
      - source ./update_vars.sh --codebuild --resourcetier $resourcetier
      - ./install-packages
      - ./init/init
      - source ./update_vars.sh --codebuild --resourcetier $resourcetier
      # - ./deploy/packer-firehawk-amis/modules/firehawk-base-ami/build.sh
      - source ./update_vars.sh --codebuild --resourcetier $resourcetier
      - ls ./deploy
      # - ansible --version
      - ./deploy/packer-firehawk-amis/modules/firehawk-ami/build.sh
  # build:
  #   commands:
  #     - source ./update_vars.sh --codebuild --resourcetier $resourcetier
  #     - cd deploy/packer-firehawk-amis/modules/firehawk-base-ami
  #     - ./build.sh
artifacts:
  files:
    - '**/*'

# batch:
#   fast-fail: false