version: 0.2

env:
  variables:
    resourcetier: dev
  parameter-store:
    onsite_public_ip: "/firehawk/resourcetier/$resourcetier/onsite_public_ip"

phases:
  install:
    commands:
      # - git submodule init
      # - git submodule update --recursive --depth 10 -j 8
      - git config pull.rebase true
      - ./gitpullrecursive --init-all
      - source ./update_vars.sh --verbose --codebuild --resourcetier $resourcetier
      - ./install-packages
      - ./init/init
  build:
    commands:
      - echo '...replace with real build commands...'

artifacts:
  files:
    - '**/*'

# batch:
#   fast-fail: false