version: 0.2

env:
  variables:
    resourcetier: dev
  parameter-store:
    onsite_public_ip: "/firehawk/resourcetier/$resourcetier/onsite_public_ip"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Version of Node in Docker Image"
      - node --version
      - python3.8 --version
      - git rev-parse HEAD
      - ./gitpullrecursive --init-all
      - mkdir -p "$HOME/.ssh/tls"
      - export PATH=$PATH:/root/.local/bin
      - echo "PATH=$PATH"
      - source ./update_vars.sh --codebuild --resourcetier $resourcetier
      - ./init/init
  build:
    commands:
      - source ./update_vars.sh --codebuild --resourcetier $resourcetier
      - ./deploy/packer-firehawk-amis/modules/firehawk-base-ami/build.sh
      - source ./update_vars.sh --codebuild --resourcetier $resourcetier
      - ./deploy/packer-firehawk-amis/modules/firehawk-ami/build.sh