version: 0.2

env:
  variables:
    resourcetier: dev
  parameter-store:
    onsite_public_ip: "/firehawk/resourcetier/$resourcetier/onsite_public_ip"

phases:
  pre_build:
    commands:
      - python3 -m pip install --user --upgrade pip
      - python3 -m pip install ansible boto3 botocore
  install:
    commands:
      - git status
      - ./gitpullrecursive --init-all
      - source ./update_vars.sh --codebuild --resourcetier $resourcetier
      - ./install-packages
      - ./init/init
  build:
    commands:
      - echo '...replace with real build commands...'

artifacts:
  files:
    - '**/*'

# batch:
#   fast-fail: false