version: 0.2

env:
  variables:
    resourcetier: dev
  parameter-store:
    onsite_public_ip: "/firehawk/resourcetier/$resourcetier/onsite_public_ip"

phases:
  # pre_build:
  #   commands:
  #     - python3 -m pip install --user --upgrade pip
  #     - python3 -m pip install ansible boto3 botocore
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python3.8 --version
      - pip --version
      - python3.8 -m pip install --upgrade pip
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip && unzip packer.zip
      - ./packer version
      - python3.8 -m pip install --user ansible boto3 botocore
      - /root/.local/bin/ansible --version
      - export PATH=$PATH:/root/.local/bin
      - ansible --version
      - git status
      - ./gitpullrecursive --init-all
      - source ./update_vars.sh --codebuild --resourcetier $resourcetier
      # - ./install-packages
      # - ./init/init
      # - source ./update_vars.sh --codebuild --resourcetier $resourcetier
      # # - ./deploy/packer-firehawk-amis/modules/firehawk-base-ami/build.sh
      # - source ./update_vars.sh --codebuild --resourcetier $resourcetier
      # - ./deploy/packer-firehawk-amis/modules/firehawk-ami/build.sh
  # build:
  #   commands:
  #     - source ./update_vars.sh --codebuild --resourcetier $resourcetier
  #     - cd deploy/packer-firehawk-amis/modules/firehawk-base-ami
  #     - ./build.sh
# artifacts:
#   files:
#     - '**/*'

# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.8
#   pre_build:
#     commands:
#       - python3.8 --version
#       - pip --version
#       - python3.8 -m pip install --upgrade pip
#       - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip && unzip packer.zip
#       - ./packer version
#       - python3.8 -m pip install --user ansible
#       - /root/.local/bin/ansible --version
#       - export PATH=$PATH:/root/.local/bin
#       - ansible --version
#       - echo 'Validate packer json'
#       - ./packer validate packer.json
#   build:
#     commands:
#       - ./packer build -color=false packer.json | tee build.log