version: 0.2

phases:
  install:
    commands:
      - git submodule init
      - git submodule update --recursive
      - source ./update_vars.sh --verbose
      - ./install-packages
      - ./init/init
  build:
    commands:
      - echo '...replace with real build commands...'

artifacts:
  files:
    - '**/*'