#!/bin/bash

set -e # exit on failure

pwd=$(pwd)

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

cd $SCRIPTDIR
git pull origin bug-vault-init --recurse
cd $pwd