#!/bin/bash

# 1st arg is the branch name

set -e # exit on failure

pwd=$(pwd)

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

cd $SCRIPTDIR
git pull origin $1 --recurse
cd $pwd