#!/bin/bash

# 1st arg is the branch name

set -e # exit on failure

pwd=$(pwd)
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script
cd $SCRIPTDIR

function options {
  branch=""

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --clear-cache)
        echo "...Clearing cache recursively"
        find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
        echo "git status"
        git status
        ;;
      --deinit-and-init-submodules)
        echo "...deinit submodules"
        git submodule deinit -f $SCRIPTDIR
        echo "...submodule update"
        git submodule update --init --recursive
        ;;
      --branch)
        branch="$2"
        shift
        ;;
    #   --help)
    #     print_usage
    #     exit
    #     ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

}

options "$@"

git pull origin $branch --recurse
cd $pwd