#!/bin/bash

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

$SCRIPTDIR/install-packages
$SCRIPTDIR/init/init
$SCRIPTDIR/vault-init/init