- hosts: localhost
  remote_user: "{{ variable_connect_as_user | default('ec2-user') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true
  any_errors_fatal: true

  vars:
  ansible_python_interpreter: "/usr/bin/python3"

  tasks:
  - name: "Create a role and attach a managed policy called 'aws-ec2-spot-fleet-tagging-role'"
    community.aws.iam_role:
      name: aws-ec2-spot-fleet-tagging-role
      assume_role_policy_document: "{{ lookup('file','policy.json') }}"
      managed_policies:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole