#!/bin/bash

# mount /rendering.dev.firehawkvfx.com nfs defaults,nolock,hard,_netdev 0 0

# 1st arg is ip address
# 2nd arg is the bucket name listed by showmount -e $1 starting without /
# 3rd args is target path

# eg: ./mount-filegateway 10.1.139.151 rendering.dev.firehawkvfx.com /Volumes/cloud_prod

# function has_yum {
#   [[ -n "$(command -v yum)" ]]
# }

# function has_apt_get {
#   [[ -n "$(command -v apt-get)" ]]
# }

# function has_brew {
#   [[ "$OSTYPE" == "darwin"* ]]
# }

# if $(has_apt_get); then
#     sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nfs-common
# elif $(has_yum); then
#     sudo yum install -y nfs-common
# elif $(has_brew); then
#     sudo brew install -y nfs-common
# else
#     echo "Could not find apt-get, yum, or brew. Cannot install dependencies on this OS."
#     exit 1
# fi

sudo umount -f "$3" # Ensure no present mount

showmount -e "$1"

sudo mkdir -p "$3"

sudo mount -t nfs -o nolock,hard $1:/$2 $3