---
# tasks file for roles/init-host

- name: Collect some facts only for ansible_distribution
  setup:
    gather_subset:
      - '!all'
      - 'min'
  tags:
  - always
  
- name: change hostname
  hostname:
    name: "{{ set_hostname }}"
  when: set_hostname is defined

- name: Update hosts file with regex if ubuntu to handle correctly.  Otherwise this https://github.com/ansible/ansible-modules-core/issues/2308
  lineinfile: dest=/etc/hosts line="127.0.0.1       localhost       localhost.localdomain       {{ set_hostname }}"
              regexp="^127\.0\.0\.1.*localhost.*$"
  when: set_hostname is defined and ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )

- name: insert/update block in /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.hostname }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.hostname }}"
  with_items:
    - { ip: "{{ onsite_private_vpn_ip }}", hostname: "{{ openfirehawkserver_name }}" }

# - name: Allow new lines from ansible shell output.  Logout or reboot for this to take effect.
#   lineinfile:
#     path: /etc/environment
#     line: "ANSIBLE_STDOUT_CALLBACK=debug"
#     create: yes
    
