#!/bin/bash

EXECDIR="$(pwd)"
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script
cd "$SCRIPTDIR"

if [[ -z "$1" ]]; then
    echo "ERROR: 1st args provided must be the resourcetier (dev / main)"
    exit 1
fi

export resourcetier="$1"
echo "resourcetier: $resourcetier"
vagrant destroy -f