#!/bin/bash

set -e

initialized="$(vault status | awk '/^Initialized/' | awk '{ print $2 }')"

if [[ "$initialized" == "false" ]]; then
    echo "Initializing vault..."
    export VAULT_ADDR=https://127.0.0.1:8200
    vault operator init -recovery-shares=1 -recovery-threshold=1
elif [[ "$initialized" == "true" ]]; then
    echo "Vault is already initialised.  Ensure you can login with a token."
fi