#!/bin/bash
set -e

exit_if_error() {
  local exit_code=$1
  shift
  [[ $exit_code ]] &&               # do nothing if no error code passed
    ((exit_code != 0)) && {         # do nothing if error code is 0
      printf 'ERROR: %s\n' "$@" >&2 # we can use better logging here
      exit "$exit_code"             # we could also check to make sure
                                    # error code is numeric when passed
    }
}

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script
namespace="$TF_VAR_vpcname-$(basename $SCRIPTDIR)"
echo "Namespace for terraform remote state: $namespace"

# Raise error if var isn't defined.
if [[ -z "$TF_VAR_resourcetier" ]]; then
    exit_if_error 1 "TF_VAR_resourcetier not defined."
fi
if [[ -z "$AWS_DEFAULT_REGION" ]]; then
    exit_if_error 1 "AWS_DEFAULT_REGION not defined."
fi
if [[ -z "$TF_VAR_bucket_extension" ]]; then
    exit_if_error 1 "TF_VAR_bucket_extension not defined."
fi

# Init the s3 bucket without the backend, since it doesn't exist yet.
terraform init \
    -input=false
terraform plan -out=tfplan -input=false

terraform apply -input=false tfplan