#!/bin/bash
set -e
EXECDIR="$(pwd)"

SOURCE=${BASH_SOURCE[0]} # resolve the script dir even if a symlink is used to this script
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

cd $SCRIPTDIR
source ../update_vars.sh

if [[ "$FH_VAR_infra_state" == "destroy" ]]; then
  echo "Will destroy infra..."
  ../deploy/destroy
else
  echo "Will deploy infra..."
  ../init/init-deploy
  ../vault-init/init
  ../vault-init/configure
  ../deploy/apply
fi
cd $EXECDIR