#!/bin/bash

FREE=`df -k --output=avail "$PWD" | tail -n1`   # df -k not df -h
# if [[ $FREE -lt 10485760 ]]; then               # 10G = 10*1024*1024k
if [[ $FREE -lt 102400 ]]; then               # 10G = 100*1024k
    echo "ERROR: less than 100MB free.  Aborting."
    exit 1
fi