#!/bin/bash

set -e # exit on failure
# set -x

EXECDIR="$(pwd)"
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

echo "USER: $USER"
export AWS_DEFAULT_REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/\(.*\)[a-z]/\1/')
echo "install_log_agent: for region $AWS_DEFAULT_REGION"
cd $SCRIPTDIR/..

date=$(date +'%Y/%m/%d/%R')

echo "Stopping cloudwatch agent"
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a stop

cd /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d

# works
echo "{\"agent\": {\"metrics_collection_interval\": 10,\"logfile\": \"/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log\"},\"logs\": { \"logs_collected\": {\"files\": {\"collect_list\": [{\"file_path\": \"/var/log/aws/codedeploy-agent/codedeploy-agent.log\",\"log_group_name\": \"codedeploy-agent-log\",\"log_stream_name\": \"{instance_id}-codedeploy-agent-log\"},{\"file_path\": \"/tmp/codedeploy-agent.update.log\", \"log_group_name\": \"codedeploy-updater-log\", \"log_stream_name\": \"{instance_id}-codedeploy-updater-log\" },{\"file_path\": \"/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log\", \"log_group_name\": \"codedeploy-deployments-log\", \"log_stream_name\": \"{instance_id}-codedeploy-deployments-log\"} ] }},\"log_stream_name\": \"codedeploy_firehawk_deploy\",\"force_flush_interval\": 15}}" >> cloudwatch.cfg

# try with date in stream name
# echo "{\"agent\": {\"metrics_collection_interval\": 10,\"logfile\": \"/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log\"},\"logs\": { \"logs_collected\": {\"files\": {\"collect_list\": [{\"file_path\": \"/var/log/aws/codedeploy-agent/codedeploy-agent.log\",\"log_group_name\": \"codedeploy-agent-log\",\"log_stream_name\": \"{instance_id}-codedeploy-agent-log\"},{\"file_path\": \"/tmp/codedeploy-agent.update.log\", \"log_group_name\": \"codedeploy-updater-log\", \"log_stream_name\": \"{instance_id}-codedeploy-updater-log\" },{\"file_path\": \"/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log\", \"log_group_name\": \"codedeploy-deployments-log\", \"log_stream_name\": \"{instance_id}-codedeploy-deployments-log-$date\"} ] }},\"log_stream_name\": \"codedeploy_firehawk_deploy\",\"force_flush_interval\": 15}}" >> cloudwatch.cfg

# this works
# echo '{"agent": {"metrics_collection_interval": 10,"logfile": "/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log"},"logs": { "logs_collected": {"files": {"collect_list": [{"file_path": "/var/log/aws/codedeploy-agent/codedeploy-agent.log","log_group_name": "codedeploy-agent-log","log_stream_name": "{instance_id}-codedeploy-agent-log"},{"file_path": "/tmp/codedeploy-agent.update.log", "log_group_name": "codedeploy-updater-log", "log_stream_name": "{instance_id}-codedeploy-updater-log" },{"file_path": "/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log", "log_group_name": "codedeploy-deployments-log", "log_stream_name": "{instance_id}-codedeploy-deployments-log"} ] }},"log_stream_name": "codedeploy_firehawk_deploy","force_flush_interval": 15}}' >> cloudwatch.cfg

# provided baseline
# echo '{"agent": {"metrics_collection_interval": 10,"logfile": "/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log"},"logs": { "logs_collected": {"files": {"collect_list": [{"file_path": "/var/log/aws/codedeploy-agent/codedeploy-agent.log","log_group_name": "codedeploy-agent-log","log_stream_name": "{instance_id}-codedeploy-agent-log"},{"file_path": "/tmp/codedeploy-agent.update.log", "log_group_name": "codedeploy-updater-log", "log_stream_name": "{instance_id}-codedeploy-updater-log" },{"file_path": "/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log", "log_group_name": "codedeploy-deployments-log", "log_stream_name": "{instance_id}-codedeploy-deployments-log"} ] }},"log_stream_name": "my_log_stream_name","force_flush_interval": 15}}' >> cloudwatch.cfg

echo "Starting cloudwatch agent"
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:cloudwatch.cfg -s
