#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

echo "USER: $USER"
cd $SCRIPTDIR/..

hash="$(git rev-parse HEAD)"
echo "COMMIT: $hash"
echo "End Deployment: Firehawk"

