#!/bin/bash

set -e

policies="$(vault token lookup | awk '/^policies/ { print $2 ; exit }')"

if [[ "$policies" == "[root]" ]]; then
    echo ""
    echo "Warning: creating an admin token and using it to login.  You should only ever run this script once."
    echo ""

    admin_token=$(vault token create -policy=admins -policy=vpn_read_config -policy=deadline_client -explicit-max-ttl=720h -field=token)
    vault login --no-print $admin_token
else
    echo "A new admin token wasn't required since you are not logged in as root.  Use 'vault token lookup' for more information."
fi