#!/bin/bash

s3_bucket_name=$(terragrunt output s3_bucket_name)

echo
echo "UBL Instructions:"
echo
echo "If you are using UBL for third party software, use the AWS Management Console for S3 to place the zip file containing the certs you wish to configure for the UBL license forwarder in the bucket path:"
echo "${s3_bucket_name}/ublcertszip/certs.zip"
echo
echo "This cert zip file is provided by Thinkbox when you purchase UBL credits for the first time for any software.  If you purchase credits for new software for the first time you must update this file."
echo
